# Default values for regnskapsregister-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##regnskapsregister-api
RREG_REGNSKAPSREGISTER_API_MEMORY: "1500Mi"
