apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    brreg.regnskapsregister-api.service: regnskapsregister-api
  name: regnskapsregister-api
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      brreg.regnskapsregister-api.service: regnskapsregister-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        brreg.regnskapsregister-api.service: regnskapsregister-api
    spec:
      containers:
      - env:
          - name: RRAPI_POSTGRES_DB_URL
            value: {{ required "Missing value RRAPI_POSTGRES_DB_URL" .Values.RRAPI_POSTGRES_DB_URL | quote }}
          - name: RRAPI_POSTGRES_DBO_USER
            value: {{ required "Missing value RRAPI_POSTGRES_DBO_USER" .Values.RRAPI_POSTGRES_DBO_USER | quote }}
          - name: RRAPI_POSTGRES_DBO_PASSWORD
            value: {{ required "Missing value RRAPI_POSTGRES_DBO_PASSWORD" .Values.RRAPI_POSTGRES_DBO_PASSWORD | quote }}
          - name: RRAPI_POSTGRES_USER
            value: {{ required "Missing value RRAPI_POSTGRES_USER" .Values.RRAPI_POSTGRES_USER | quote }}
          - name: RRAPI_POSTGRES_PASSWORD
            value: {{ required "Missing value RRAPI_POSTGRES_PASSWORD" .Values.RRAPI_POSTGRES_PASSWORD | quote }}
          - name: RRAPI_SFTP_SERVER
            value: {{ required "Missing value RRAPI_SFTP_SERVER" .Values.RRAPI_SFTP_SERVER | quote }}
          - name: RRAPI_SFTP_USER
            value: {{ required "Missing value RRAPI_SFTP_USER" .Values.RRAPI_SFTP_USER | quote }}
          - name: RRAPI_SFTP_PASSWORD
            value: {{ required "Missing value RRAPI_SFTP_PASSWORD" .Values.RRAPI_SFTP_PASSWORD | quote }}
          - name: RRAPI_SFTP_PORT
            value: {{ required "Missing value RRAPI_SFTP_PORT" .Values.RRAPI_SFTP_PORT | quote }}
          - name: RRAPI_SFTP_DIRECTORY
            value: {{ required "Missing value RRAPI_SFTP_DIRECTORY" .Values.RRAPI_SFTP_DIRECTORY | quote }}
          - name: RRAPI_SLACK_TOKEN
            value: {{ required "Missing value RRAPI_SLACK_TOKEN" .Values.RRAPI_SLACK_TOKEN | quote }}
        name: regnskapsregister-api
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value RREG_REGNSKAPSREGISTER_API_MEMORY" .Values.RREG_REGNSKAPSREGISTER_API_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always
status: {}
