apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    brreg.regnskapsregister-api.service: regnskapsregister-api
  name: regnskapsregister-api
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    brreg.regnskapsregister-api.service: regnskapsregister-api
status:
  loadBalancer: {}
